version: '2'
services:
    php:
        build: php-fpm
        container_name: genesis_php
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached

    nginx:
        build: nginx
        container_name: genesis_nginx
        ports:
            - '80:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached